max_name: 30
min_name: 5
min_password: 6
min_description: 10
max_for_limit: 5
per_page: 5
truncate_description: 90
description_event: 360
min_location: 5
update: "Update"
create: "Create"
per_page_album: 9
per_page_image: 12
per_page_event: 6
new_description: 9
new_content: 9
edit_description: 6
min_rate: 1
max_rate: 5
round_float: 1
max_show_comment: 5
min_title: 10
new_detail: 20
event_user: 6
event_new: 2
club_member: 6
event_type: 2
