max_name: 100
languages: {en: "english", vi: "vietnamese", jp: "japanese"}
max_name: 30
min_name: 5
min_password: 6
min_description: 10
max_description: 400
max_for_limit: 5
per_page: 5
truncate_description: 90
truncate_organization: 30
description_event: 360
max_location: 150
delete: "delete"
comment: "comment"
edit: "edit"
update: "Update"
create: "Create"
per_page_album: 9
per_page_image: 12
per_page_event: 6
new_description: 9
new_content: 9
edit_description: 6
min_rate: 1
max_rate: 5
max_for_rating: 6
round_float: 1
max_show_comment: 5
min_title: 10
new_detail: 100
event_user: 10
event_new: 4
club_member: 6
event_type: 3
min_title: 10
min_content: 10
club_event: 4
event_news: 4
club_member: 6
club_per_page: 4
organization_per_page: 3
my_clubs: "/clubs"
spend: 1
consum: 2
inprocess: "inprocess"
finished: "finished"
event: "Event"
spend_money: 1
none: 0
min_line: 0
max_line: 6
refresh: 60
joined: "joined"
pending: "pending"
reject: "reject"
en: "English"
vi: "Việt Nam"
jp: "日本語"
english: "english"
vietnamese: "vietnamese"
japanese: "japanese"
payment_budget: "Payment For Club Of Month:"
periodic_category: 4
payment_budget: "Payment For Club Of Month:"
member_club: 14
club_member: 18
notification: 3
get_money: 2
pay_money: 1
event_page: 4
member_manager: 23
notification_event: "Event"
notification_club: "Club"
my_url: "http://club.framgia.vn/"
limit_tags: 4
error_import: "error when input file"
error_data: "has user exist"
read_key_row1: 1
read_data_row2: 2
limit_comments: 7
chat_messages_limit: 30
min_content: 20
ratings: "ratings"
truncate:
  club:
    description: 100
messages_load_more: 30
subsidy: "subsidy"
pay_money: "pay_money"
get_money: "get_money"
max_exspene: 9
