max_name: 100
languages: {en: "english", vi: "vietnamese", jp: "japanese"}
max_name: 30
min_name: 5
min_password: 6
min_description: 10
max_for_limit: 5
per_page: 5
truncate_description: 90
truncate_organization: 30
description_event: 360
min_location: 5
delete: "delete"
edit: "edit"
update: "Update"
create: "Create"
per_page_album: 9
per_page_image: 12
per_page_event: 6
new_description: 9
new_content: 9
edit_description: 6
min_rate: 1
max_rate: 5
max_for_rating: 6
round_float: 1
max_show_comment: 5
min_title: 10
new_detail: 100
event_user: 6
event_new: 4
club_member: 6
event_type: 3
min_title: 10
min_content: 10
club_event: 4
event_news: 4
club_member: 6
club_per_page: 4
organization_per_page: 3
my_clubs: "/clubs"
spend: 1
consum: 2
inprocess: "inprocess"
finished: "finished"
event: "Event"
spend_money: 1
none: 0
min_line: 0
max_line: 6
refresh: 60
joined: "joined"
pending: "pending"
reject: "reject"
en: "English"
vi: "Việt Nam"
jp: "日本語"
english: "english"
vietnamese: "vietnamese"
japanese: "japanese"
payment_budget: "Payment For Club Of Month:"
periodic_category: 4
